Feature/character turn
robinferm/chinese-checkers pull request #47
Opened 2021-10-04 07:21 UTC by Farhadtavakoli

2021-10-04 08:52 UTC, robinferm requested changes

2021-10-04 08:52 UTC, robinferm commented on chinese-checkers.Core/Models/GameSession.cs
> +
Ta bort onödiga spaces

2021-10-04 08:52 UTC, robinferm commented on chinese-checkers.Core/Models/GameSession.cs
> +            CurrentlyPlaying.Highligh = false;
Stavfel på highlight

2021-10-04 08:52 UTC, robinferm commented on chinese-checkers/Helpers/DrawHelper.cs
> +                            framePosition = new Vector2(ScalingHelper.CalculateX(8, -4) + (150 * ScalingHelper.ScaleXY), ScalingHelper.CalculateY(-4));
Det är exakt samma kod i else som i if. Ta bort else

2021-10-04 08:52 UTC, robinferm commented on chinese-checkers/Helpers/DrawHelper.cs
> +                    args.DrawingSession.DrawImage(ScalingHelper.Img(abilitys[player.Character.GetType().Name], .5f), abilityPosition);
Samma kod i else som if här också. Ta bort else

2021-10-04 08:52 UTC, robinferm commented on chinese-checkers/Helpers/ScalingHelper.cs
> -            return positioning + centering;
Varför ta bort centering?

2021-10-04 08:52 UTC, robinferm commented on chinese-checkers/Views/MainPage.xaml.cs
> +        public Player Player { get; set; }
Den här används inte, 0 references

2021-10-04 08:52 UTC, robinferm commented on chinese-checkers/Helpers/DrawHelper.cs
> +        public static void DrawCharacterAndAbility(ICanvasAnimatedControl sender, CanvasAnimatedDrawEventArgs args, List<Player> players, Dictionary<string, CanvasBitmap> frames, Dictionary<string, C
bool isTurn används inte

2021-10-04 08:52 UTC, robinferm commented on chinese-checkers/Views/MainPage.xaml.cs
> +                DrawHelper.DrawCharacterAndAbility(sender, args, gs.Players, characterFrames, characterAbility, highlightCharacter,false);
Eftersom bool isTurn inte används så gör if och else exakt samma sak här

2021-10-04 08:55 UTC, robinferm commented on chinese-checkers/Helpers/DrawHelper.cs
>                          framePosition = new Vector2(ScalingHelper.CalculateX(12, 0) + ((180 * ScalingHelper.ScaleXY) - ScalingHelper.ScalingValue), ScalingHelper.CalculateY(0) - (ScalingHelper.Scalin
Detta är unreachable code

2021-10-05 08:56 UTC, Farhadtavakoli commented on chinese-checkers/Views/MainPage.xaml.cs
> +            gs.CurrentlyPlaying.Highligh = true;
To make a character highlighted for the first time when the player starts a new game.

2021-10-06 07:18 UTC, merged